services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: ghostnet
      MYSQL_USER: ghostnet
      MYSQL_PASSWORD: ghostnet
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"  
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
