spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ghostnet?allowPublicKeyRetrieval=true&sslMode=DISABLED&serverTimezone=UTC
    username: ghostnet
    password: ghostnet
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
server:
  port: 8080
